device:
  layer: rpi3
  storage_type: sd
  hostname: vibe-os-rpi3bplus
  user1: vibe
  user1sudo: passwd
  user1groups: adm,dialout,cdrom,audio,users,video,games,plugdev,input,spi,i2c,gpio,render

image:
  layer: image-rpios
  name: vibe-coders-os-rpi3bplus
  compression: zstd
  boot_part_size: 512M
  root_part_size: 16G

layer:
  base: trixie-minbase
  vibe: vibe-os

locale:
  default: en_IN.UTF-8
  keyboard_keymap: us
  keyboard_layout: English (US)
  timezone: Asia/Kolkata
